apiVersion: v1
kind: ConfigMap
metadata:
  name: net-config
  namespace: vpntest
data:
  IPSEC_VIRTUAL_PRIVATE: %v4:10.0.0.0/8,%v4:192.168.0.0/16,%v4:172.16.0.0/12
  VPN_PUBLIC_IP: 100.73.69.118W
  XL2TPD_IP_NET: 52.0.0../24
  XL2TPD_IP_RANGE: 52.0.0.100-52.0.0.199
  XL2TPD_LOCAL_IP: 52.0.0.201